BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Alunos CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Instrutores CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE Instrutores (
    id_instrutor NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    especialidade VARCHAR2(50)
)
/
CREATE TABLE Alunos (
    id_aluno NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    id_instrutor_responsavel NUMBER(10),
    CONSTRAINT fk_instrutor
        FOREIGN KEY(id_instrutor_responsavel) 
        REFERENCES Instrutores(id_instrutor)
)
/
INSERT INTO Instrutores (nome, especialidade) VALUES ('Carlos Souza', 'Musculação')
/
INSERT INTO Instrutores (nome, especialidade) VALUES ('Ana Silva', 'Pilates')
/
INSERT INTO Instrutores (nome, especialidade) VALUES ('Bruno Costa', 'Funcional')
/
INSERT INTO Alunos (nome, email, id_instrutor_responsavel) VALUES ('Maria Joaquina', 'maria@email.com', 1)
/
INSERT INTO Alunos (nome, email, id_instrutor_responsavel) VALUES ('João Pedro', 'joao@email.com', 2)
/
INSERT INTO Alunos (nome, email, id_instrutor_responsavel) VALUES ('Fernanda Lima', 'fe@email.com', 1)
/
COMMIT
/